@startuml

title NewEmploeyee Sequence


Boss->HRBoss: request_for_employer
activate HRBoss

HRBoss->HRDepartment: find candidates
activate HRDepartment

HRDepartment ->HRDepartment: collect candidates
HRDepartment ->HRBoss: return candiates
deactivate HRDepartment


HRBoss->Boss: return candidates

deactivate HRBoss
activate Boss

create Candidates
Boss ->Candidates: choose candidate
activate Candidates
Candidates -> Boss : return candidate
deactivate Candidates


Boss -> Deparment : hire candidate
deactivate Boss

@enduml