@startuml
participant OneClass
activate OneClass
[o-> OneClass:
create Instance
OneClass->Instance : new


OneClass->Instance : message
activate Instance

OneClass<--Instance : return

Instance<-Instance : self call
activate Instance
deactivate Instance

OneClass->Instance : messageText
activate Instance
OneClass->Instance : messageText2
deactivate Instance

deactivate Instance

OneClass->Instance : delete
destroy Instance
deactivate OneClass

@enduml